version: '3.3'

services:

  mongodb:
    command: mongod --noauth
    container_name: mongodb
    image: mongo:4.4.5-bionic
    network_mode: host
    ports:
      - "27017:27017"
    volumes:
      - .:/code/

  mongo_seed:
    #tty: true
    command: /code/restore-mongodb-dump.sh
    container_name: mongo_seed
    image: mongo:4.4.5-bionic
    depends_on:
      - mongodb
    network_mode: host
    volumes:
      - .:/code/

  web:
    build: .
    command: uvicorn app.main:app
    container_name: web
    depends_on:
      - mongodb
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - .:/code/app/